# Generated by Django 3.2 on 2023-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_cab',
            name='nro_ticket',
            field=models.IntegerField(default=0),
        ),
    ]
