# Generated by Django 3.2 on 2023-07-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_cab_nro_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_cab',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
