# Generated by Django 3.2 on 2023-07-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_cab_nro_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='documento',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
