# Generated by Django 3.2 on 2023-07-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_proveedores_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_det',
            name='ticketCabId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.ticket_cab'),
        ),
    ]
