# Generated by Django 3.2 on 2023-07-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_ticket_det_ticketcabid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_det',
            name='peso1',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_det',
            name='peso2',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_det',
            name='peso_bruto',
            field=models.IntegerField(blank=True, default=0.0, null=True),
        ),
    ]
