# Generated by Django 3.2 on 2023-08-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20230728_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_cab',
            name='chofer',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket_cab',
            name='matricula',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
